name: no_free_action
description: A NO-FREE-USAGE Bot for github. (Only worked with github action.)
version: 1.0.1
homepage: https://github.com/fluttercandies/no-free-usage-action

environment:
  sdk: '>=2.8.1 <=3.0.0'

dependencies:
  args: ^1.6.0
  http: ^0.12.2
  meta: ^1.2.3

dev_dependencies:
  effective_dart: ^1.2.4
  pedantic: ^1.9.2
